WATCHER_PROCESSING_MODE = "auto"
WATCHER_NOTIFICATION_SOURCE = "watcher"
START_SCAN_PROCESSING_MODE = "start_scan"
START_SCAN_NOTIFICATION_SOURCE = "start_scan"

BACKGROUND_NOTIFICATION_SOURCES = frozenset(
    {
        WATCHER_NOTIFICATION_SOURCE,
        START_SCAN_NOTIFICATION_SOURCE,
    }
)
