LIGHT_THEME = {
    "window_background": "#F6F7F9",
    "card_background": "#FFFFFF",
    "surface_background": "#F9FAFB",
    "text_primary": "#111827",
    "text_secondary": "#6B7280",
    "text_body": "#374151",
    "text_detail": "#4B5563",
    "text_muted": "#9CA3AF",
    "text_disabled": "#CBD5E1",
    "text_disabled_strong": "#D1D5DB",
    "border": "#E5E7EB",
    "border_subtle": "#EEF2F7",
    "border_muted": "#EEF0F3",
    "button_primary": "#2563EB",
    "button_primary_hover": "#1D4ED8",
    "button_on_primary": "#FFFFFF",
    "button_primary_soft": "#EEF4FF",
    "button_primary_soft_strong": "#E8F0FF",
    "button_primary_border": "#BFDBFE",
    "button_danger": "#EF4444",
    "button_danger_hover": "#DC2626",
    "button_secondary": "#F3F4F6",
    "input_background": "#FFFFFF",
    "warning_background": "#FFFBEB",
    "warning_border": "#FDE68A",
    "warning_text": "#92400E",
    "log_background": "#111827",
    "log_border": "#1F2937",
    "log_text": "#E5E7EB",
    "shadow_rgba": (20, 24, 31, 14),
}
